trigger:
- main

pool:
  name: 'LocalPool'

variables:
  acrName: 'fcgregistries.azurecr.io'
  dockerRegistryServiceConnection: '576941a1-c337-49cf-af7a-81750fcd6af9'
  tag: '$(Build.BuildId)'
  buildContext: '$(Build.SourcesDirectory)'  # build context ajustado para enxergar tudo

stages:
- stage: BuildAndPush
  displayName: Build and Push Games API
  jobs:
  - job: BuildGamesApi
    displayName: Build FCG-Games API
    steps:
    - task: Docker@2
      displayName: Build and Push Games API Image
      inputs:
        command: buildAndPush
        repository: 'fcg-games-api'
        dockerfile: '$(Build.SourcesDirectory)/FCG-Games.Api/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(buildContext)
        tags: |
          $(tag)