apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-consumer
  namespace: fcg-users
  labels:
    app: users-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-consumer
  template:
    metadata:
      labels:
        app: users-consumer
    spec:
      containers:
      - name: users-consumer
        image: alexandresorza/fcg-users-consumer:latest
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: fcg-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ApplicationInsights__ConnectionString
          valueFrom:
            secretKeyRef:
              name: fcg-secrets
              key: appinsights-connection-string
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: fcg-secrets
              key: sql-users-connection
        - name: ServiceBus__ConnectionString
          valueFrom:
            secretKeyRef:
              name: fcg-secrets
              key: servicebus-connection
        - name: ServiceBus__Topics__Users
          valueFrom:
            configMapKeyRef:
              name: fcg-config
              key: TOPIC_USERS
        - name: ServiceBus__Subscriptions__Users
          valueFrom:
            configMapKeyRef:
              name: fcg-config
              key: SUB_USERS
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "fcg-keyvault-secrets"

